### PR TITLE
Allow testing PRs in blackbox tests

### PR DESCRIPTION
**Pull request by jbaublitz**
This will support the automation work that I'm doing for blackbox testing.

### CODE REVIEW

**Comment by jbaublitz** [comment]
@mulkieran This will allow ansible to set the added environment variables to check out PR branches to run the blackbox tests.

**Comment by mulkieran** [comment]
> @mulkieran This will allow ansible to set the added environment variables to check out PR branches to run the blackbox tests.

AFAICT, this change will not affect the blackbox tests at all. There's a script in the blackbox directory, reset_upstream_stratis_repos.sh, which might be the one that matters.

**Comment by jbaublitz** [comment]
Oh! I'll take this out of review then and dig into this a little more.

**Comment by bgurney-rh** [comment]
I was thinking that a conditional state for running "reset_upstream_stratis_repos.sh" would be nice for situations where the user running the blackbox test wants to do something other than a "remove-and-reclone" operation (which is what it does now).

**Comment by jbaublitz** [comment]
@mulkieran @bgurney-rh The new commit and revert commit should resolve the issue.

**Comment by jbaublitz** [comment]
Found one last problem. Fixing now.

**Comment by jbaublitz** [comment]
Fixed. Rerequesting review for the last commit.

**Pull request closed without merging**
