### PR TITLE
Add generate_test_config script

### PR DESCRIPTION
**Pull request by bgurney-rh**

### CODE REVIEW

**Comment by bgurney-rh** [comment]
Rebased.

**Review by mulkieran — CHANGES_REQUESTED** [review]
Might as well move the ```cancel_jobs``` script into this new directory as well.

**Comment by bgurney-rh** [comment]
Do you mean the `batch_cancel.py` script?  That's referenced by the Makefile for various tasks (fmt, lint, etc.).

**Review by mulkieran — APPROVED** [review]

**Review by mulkieran — APPROVED** [review]
This looks fine to me. If you're satisfied with it, then you should go ahead and merge it.

**Comment by bgurney-rh** [comment]
I'm going to create a new PR, to squash the formatting fix into the main commit.

**Pull request closed without merging**
