### PR TITLE
Advance current development environment to Fedora 37

### PR DESCRIPTION
**Pull request by bgurney-rh**
Related: stratis-storage/project#544

### CODE REVIEW

**Review by mulkieran — CHANGES_REQUESTED** [review]
Please pick off the second commit and put it up for review in a separate PR.

**Comment by mulkieran** [comment]
Plz rebase.

**Comment by bgurney-rh** [comment]
Rebased.

**Review by mulkieran — APPROVED** [review]

**Comment by bgurney-rh** [comment]
Rebased.

**Pull request merged**
