### PR TITLE
Add test suite for packaged rust installations

### PR DESCRIPTION
**Pull request by bgurney-rh**
Signed-off-by: Bryan Gurney <bgurney@redhat.com>

### CODE REVIEW

**Comment by bgurney-rh** [comment]
Admittedly, I wanted to quickly get something running, to prove that it was possible, while I was reluctant to get the "plumbing" necessary to have the same file handle the two scenarios (rustup-provided rust versus package-provided rust).

The original "runalltests.sh" blindly installs rustup, while the "runalltests.sh" in this PR does not, and runs under the assumption that rust is already installed via a package, and tries to print out the current rust version to help failure diagnosis.

The "chlidren" scripts that are called (for stratisd, stratisd_nonrust, and cli) currently assume that rustup is installed, and sets them to a specific version; for the "packaged" variant, it would not do this, since rustup would not exist.  There might be a more graceful way to detect whether rustup is installed, and if not, just try to print the current version of rust being used.

**Comment by mulkieran** [comment]
We have a month to think this over now before the next Rust release.

**Comment by mulkieran** [comment]
We'll need to evaluate if this is still what we need. The primary purpose was karma giving, and we seem to be getting along without these changes ok.

**Comment by mulkieran** [comment]
@bgurney-rh: Do you think we still need this, or are we getting along ok w/out these changes?

**Comment by bgurney-rh** [comment]
I think we're okay for now.  Instead of adding new script files, there may be a potential way to add conditional statements for the rustup commands.  Even if that proves too challenging, the "install_rustup" stage in runalltests.sh, and the "rustup default" commands in each of the test scripts can be commented out, or deleted, to allow a packaged rust install to run the tests with whatever version of Rust happens to be installed on the system.

Is checking for the existence of "/usr/bin/rustc" a good enough potential test for a packaged install of a Rust system?

**Comment by bgurney-rh** [comment]
Closing this for now. We can re-evaluate later, but right now, it's not that hard to pre-install Rust via packages, and comment/delete the lines in the tests that install rustup, and configure to the lowest supported Rust version (i.e. `rustup default 1.43.0`).

**Comment by mulkieran** [comment]
@bgurney-rh: ok, thx for looking.

**Pull request closed without merging**
