### PR TITLE
blackbox: add clevis-luks Requires to stratis-cli spec

### PR DESCRIPTION
**Pull request by bgurney-rh**

### CODE REVIEW

**Comment by bgurney-rh** [comment]
I had a test system for running the blackbox tests, but it didn't have clevis-luks installed.  The build-and-package stage passed, but all of the tests encountered errors, which were related to clevis-luks not being installed.  After adding `Requires:       clevis-luks >= 15` to the stratis-cli spec file, the installation of the stratis-cli package results in the automatic installation of clevis-luks, and all tests pass.

We did add clevis and clevis-luks to the dependencies_fedora.sh script, but that needs to be manually executed (unless it's called via the runalltests.sh or rustadvtest.sh scripts).  However, after this PR, it's possible to prove that clevis-luks is not a build requirement, by removing the package prior to the blackbox test run.

**Comment by mulkieran** [comment]
@bgurney-rh: stratis-cli has no direct dependency on clevis. Can you try adding it to the stratisd spec instead?

**Comment by bgurney-rh** [comment]
Done; I added it to the stratisd spec (via a force-push), and it still passes the blackbox tests.

**Review by mulkieran — APPROVED** [review]

**Review by jbaublitz — APPROVED** [review]

**Review by jbaublitz — COMMENTED** [review]
Does clevis-luks pull in the clevis package? That's needed too.

**Comment by mulkieran** [comment]
> Does clevis-luks pull in the clevis package? That's needed too.

Yes, according to my experiment.

**Pull request merged**
