### PR TITLE
Batch cancel script

### PR DESCRIPTION
**Pull request by jbaublitz**

### CODE REVIEW

**Comment by jbaublitz** [comment]
See [here](https://github.com/stratis-storage/stratisd/actions) for the batch-cancelled jobs in stratisd.

The usage is something like `batch_cancel.py stratis-storage stratisd jbaublitz` which would cancel all CI runs that I've started in `stratis-storage/stratisd`.

**Review by bgurney-rh — APPROVED** [review]

**Review by mulkieran — CHANGES_REQUESTED** [review]
This looks fine to me. Please close and open final PR.

**Comment by mulkieran** [comment]
@jbaublitz Whoops, please switch to PyGitHub 1.45.

**Comment by jbaublitz** [comment]
> @jbaublitz Whoops, please switch to PyGitHub 1.45.

We should maybe reconsider that given that PyPi does not have anything past 1.54: https://pypi.org/project/PyGithub/#history. I pinned it to the latest version available in pip.

**Pull request closed without merging**
