### PR TITLE
Add coverage requirement to cli Jenkins tests

### PR DESCRIPTION
**Pull request by mulkieran**
Related: https://github.com/stratis-storage/project/issues/108.

### CODE REVIEW

**Comment by mulkieran** [comment]
Depends on https://github.com/stratis-storage/stratis-cli/pull/416.

**Comment by mulkieran** [comment]
@bgurney-rh I think that now that stratis-cli change is in you should be able to test this change pretty easily.

**Comment by bgurney-rh** [comment]
One note: the runalltests.sh script is not part of the automated CI (it's a "helper" script to run on a system, to help install all of the dependencies for running tests).

I checked the existing CI systems that test cli, and they do have the "python3-coverage" package already (perhaps via dependency; I'll double-check on a freshly installed system).

**Comment by bgurney-rh** [comment]
Looking at a fresh VM's install stdout from runalltests.sh, "python3-coverage" was installed as a dependency.  So in this case, adding it as an explicit install should ideally work the same as it does now (aside from being explicitly installed).

**Comment by mulkieran** [comment]
> Looking at a fresh VM's install stdout from runalltests.sh, "python3-coverage" was installed as a dependency. So in this case, adding it as an explicit install should ideally work the same as it does now (aside from being explicitly installed).

I guess it's probably best then to keep it as an explicit dependency?

**Comment by bgurney-rh** [comment]
> I guess it's probably best then to keep it as an explicit dependency?

Yes, I agree with keeping it as an explicit dependency.

**Comment by bgurney-rh** [comment]
This is what I see so far:
```
python3 -m coverage report -m --fail-under=100 --show-missing --include="./src/*"
Name                                      Stmts   Miss Branch BrPart  Cover   Missing
-------------------------------------------------------------------------------------
src/stratis_cli/__init__.py                   3      0      0      0   100%
src/stratis_cli/_actions/__init__.py          8      0      0      0   100%
src/stratis_cli/_actions/_connection.py      11      0      2      0   100%
src/stratis_cli/_actions/_constants.py        8      0      0      0   100%
src/stratis_cli/_actions/_data.py            49      0      6      0   100%
src/stratis_cli/_actions/_formatting.py      33      1      8      0    98%   39
src/stratis_cli/_actions/_logical.py         87      0     22      0   100%
src/stratis_cli/_actions/_physical.py        27      0      8      0   100%
src/stratis_cli/_actions/_stratis.py         11      0      2      0   100%
src/stratis_cli/_actions/_top.py             93      0     18      0   100%
src/stratis_cli/_error_reporting.py          28      0      2      0   100%
src/stratis_cli/_errors.py                   40      0      0      0   100%
src/stratis_cli/_main.py                     24      0      4      0   100%
src/stratis_cli/_parser/__init__.py           2      0      0      0   100%
src/stratis_cli/_parser/_logical.py           3      0      0      0   100%
src/stratis_cli/_parser/_parser.py           36      0     10      0   100%
src/stratis_cli/_parser/_physical.py          3      0      0      0   100%
src/stratis_cli/_parser/_pool.py              3      0      0      0   100%
src/stratis_cli/_stratisd_constants.py       23      0      0      0   100%
src/stratis_cli/_version.py                   3      0      2      0   100%
-------------------------------------------------------------------------------------
TOTAL                                       495      1     84      0    99%
make: *** [Makefile:53: coverage-no-html] Error 2
Completed stratis-cli test: status 2
```

**Comment by mulkieran** [comment]
@bgurney-rh Ok, cool. Please go ahead and do whatever testing you require. If it fails the 100% requirement, that will be very interesting, I'ld definitely like to take a look. (Actually, if it fails in any way).

**Comment by mulkieran** [comment]
> @bgurney-rh Ok, cool. Please go ahead and do whatever testing you require. If it fails the 100% requirement, that will be very interesting, I'ld definitely like to take a look. (Actually, if it fails in any way).

Hah! I'll take a look after my meeting (maybe tomorrow morning). Thanks!

**Comment by bgurney-rh** [comment]
One other cosmetic element: I don't see verbose test info in the previous test items:
```
python3 -m coverage --version
Coverage.py, version 4.5.1 with C extension
Documentation at https://coverage.readthedocs.io
python3 -m coverage run --timid --branch -m pytest ./tests/whitebox/integration
========================================== test session starts ==========================================
platform linux -- Python 3.7.3, pytest-3.10.1, py-1.7.0, pluggy-0.8.1
rootdir: /root/ci/workspace/stratis-cli, inifile:
plugins: hypothesis-3.66.11
collected 64 items                                                                                      

tests/whitebox/integration/test_parser.py ....                                                    [  6%]
tests/whitebox/integration/test_stratis.py .....                                                  [ 14%]
tests/whitebox/integration/logical/test_create.py sss.                                            [ 20%]
tests/whitebox/integration/logical/test_destroy.py sss.                                           [ 26%]
tests/whitebox/integration/logical/test_list.py ..s....                                           [ 37%]
tests/whitebox/integration/logical/test_rename.py ......                                          [ 46%]
tests/whitebox/integration/logical/test_snapshot.py ....                                          [ 53%]
tests/whitebox/integration/physical/test_list.py ......                                           [ 62%]
tests/whitebox/integration/pool/test_add.py ........                                              [ 75%]
tests/whitebox/integration/pool/test_create.py ...                                                [ 79%]
tests/whitebox/integration/pool/test_destroy.py ....                                              [ 85%]
tests/whitebox/integration/pool/test_list.py ....                                                 [ 92%]
tests/whitebox/integration/pool/test_rename.py .....                                              [100%]

================================= 57 passed, 7 skipped in 59.41 seconds =================================
python3 -m coverage run --timid --branch -a -m pytest ./tests/whitebox/unittest
========================================== test session starts ==========================================
platform linux -- Python 3.7.3, pytest-3.10.1, py-1.7.0, pluggy-0.8.1
rootdir: /root/ci/workspace/stratis-cli, inifile:
plugins: hypothesis-3.66.11
collected 23 items                                                                                      

tests/whitebox/unittest/test_error_fmt.py ............                                            [ 52%]
tests/whitebox/unittest/test_timeout.py ...........                                               [100%]

======================================= 23 passed in 1.12 seconds =======================================
python3 -m coverage run --timid --branch -a -m pytest ./tests/whitebox/monkey_patching/test_keyboard_interrupt.py
========================================== test session starts ==========================================
platform linux -- Python 3.7.3, pytest-3.10.1, py-1.7.0, pluggy-0.8.1
rootdir: /root/ci/workspace/stratis-cli, inifile:
plugins: hypothesis-3.66.11
collected 1 item                                                                                        

tests/whitebox/monkey_patching/test_keyboard_interrupt.py .                                       [100%]

======================================= 1 passed in 2.07 seconds ========================================
```

(This would need to be reconfigured in a stratis-cli PR, but I figured I'd paste the results now, since it's part of the added test being executed in CI.)

Does the "coverage" module have an equivalent to the pytest option "--verbose"?

**Comment by mulkieran** [comment]
I think that https://github.com/stratis-storage/stratis-cli/pull/417 should bring coverage up to 100% in tests.

**Comment by mulkieran** [comment]
Temporarily blocked by https://github.com/stratis-storage/stratis-cli/pull/417

**Comment by mulkieran** [comment]
@bgurney-rh As regards testing during coverage, it's probably preferable not to be verbose.  The reason is that we will already have run the tests in a verbose manner normally, and if any of the tests fail, then the coverage step will not be run at all. So, a terser output for the actual coverage tests is probably desirable. But it will be easy to change this later, if we find that that is not true.

**Comment by mulkieran** [comment]
@bgurney-rh This is unblocked and ready to be re-tested.

**Comment by bgurney-rh** [comment]
Looks good.
```
python3 -m coverage report -m --fail-under=100 --show-missing --include="./src/*"
Name                                      Stmts   Miss Branch BrPart  Cover   Missing
-------------------------------------------------------------------------------------
src/stratis_cli/__init__.py                   3      0      0      0   100%
src/stratis_cli/_actions/__init__.py          8      0      0      0   100%
src/stratis_cli/_actions/_connection.py      11      0      2      0   100%
src/stratis_cli/_actions/_constants.py        8      0      0      0   100%
src/stratis_cli/_actions/_data.py            49      0      6      0   100%
src/stratis_cli/_actions/_formatting.py      32      0      8      0   100%
src/stratis_cli/_actions/_logical.py         87      0     22      0   100%
src/stratis_cli/_actions/_physical.py        27      0      8      0   100%
src/stratis_cli/_actions/_stratis.py         11      0      2      0   100%
src/stratis_cli/_actions/_top.py             93      0     18      0   100%
src/stratis_cli/_error_reporting.py          28      0      2      0   100%
src/stratis_cli/_errors.py                   40      0      0      0   100%
src/stratis_cli/_main.py                     24      0      4      0   100%
src/stratis_cli/_parser/__init__.py           2      0      0      0   100%
src/stratis_cli/_parser/_logical.py           3      0      0      0   100%
src/stratis_cli/_parser/_parser.py           36      0     10      0   100%
src/stratis_cli/_parser/_physical.py          3      0      0      0   100%
src/stratis_cli/_parser/_pool.py              3      0      0      0   100%
src/stratis_cli/_stratisd_constants.py       23      0      0      0   100%
src/stratis_cli/_version.py                   3      0      2      0   100%
-------------------------------------------------------------------------------------
TOTAL                                       494      0     84      0   100%

# git log --format='%h %ai :: %s' | head -20
9b46cc9 2019-11-19 11:32:03 -0500 :: Merge pull request #417 from mulkieran/develop-import-error
ec93ceb 2019-11-19 08:40:46 -0500 :: Do not require coverage anywhere on conditional import behavior
9ced166 2019-11-18 11:43:15 -0500 :: Merge pull request #416 from mulkieran/develop-coverage
3b0bdc5 2019-11-18 10:37:24 -0500 :: Split coverage target into regular and sub-target
...
```

**Pull request merged**
