### PR TITLE
ci: add RUST_CARGO_PATH variable check

### PR DESCRIPTION
**Pull request by bgurney-rh**

### CODE REVIEW

**Comment by bgurney-rh** [comment]
The general theory of operation is that, after all of the dependencies are installed (i.e.: rust, and packages), the test machine user runs this command:
```
sudo -E ../cli_with_stratisd.sh
```
...after having exported the WORKSPACE and RUST_CARGO_PATH variables.

**Comment by jbaublitz** [comment]
@drckeefe I don't think I understand what you mean. Are you saying we shouldn't be checking if the environment is empty or not?

**Comment by drckeefe** [comment]
> @drckeefe I don't think I understand what you mean. Are you saying we shouldn't be checking if the environment is empty or not?



> @drckeefe I don't think I understand what you mean. Are you saying we shouldn't be checking if the environment is empty or not?

I believe that the script can set the variable and shouldn't have to check whether there is an existing value.

**Comment by drckeefe** [comment]
> > @drckeefe I don't think I understand what you mean. Are you saying we shouldn't be checking if the environment is empty or not?
> 
> > @drckeefe I don't think I understand what you mean. Are you saying we shouldn't be checking if the environment is empty or not?
> 
> I believe that the script can set the variable and shouldn't have to check whether there is an existing value.

I see the path must be set by the user outside of the script.

**Comment by bgurney-rh** [comment]
I realized that runalltests.sh might need to export RUST_CARGO_PATH, but I can add that in a separate PR later.

I'm going to force-push the same changes onto the other test scripts that use the cargo path.

**Comment by mulkieran** [comment]
This is superceded by https://github.com/stratis-storage/stratisd/pull/1673 and https://github.com/stratis-storage/devicemapper-rs/pull/511.

**Pull request closed without merging**
