### PR TITLE
Update vendor tarfile creation options

### PR DESCRIPTION
**Pull request by bgurney-rh**
Related https://github.com/stratis-storage/ci/issues/301

### CODE REVIEW

**Comment by bgurney-rh** [comment]
I ran the blackbox tests on a set of packages built with this; they all passed.

**Comment by mulkieran** [comment]
```
$ tar --list -v -f stratisd-3.3.0-vendor.tar.gz  |& head
drwxrwx--- 0/0               0 2022-09-29 20:52 vendor/
drwxrwx--- 0/0               0 2022-09-29 20:52 vendor/log/
-rw-r----- 0/0            1096 2022-09-29 20:52 vendor/log/LICENSE-MIT
drwxrwx--- 0/0               0 2022-09-29 20:52 vendor/log/src/
-rw-r----- 0/0            8751 2022-09-29 20:52 vendor/log/src/macros.rs
-rw-r----- 0/0           13128 2022-09-29 20:52 vendor/log/src/serde.rs
-rw-r----- 0/0           61709 2022-09-29 20:52 vendor/log/src/lib.rs
drwxrwx--- 0/0               0 2022-09-29 20:52 vendor/log/src/kv/
-rw-r----- 0/0            2221 2022-09-29 20:52 vendor/log/src/kv/error.rs
-rw-r----- 0/0            3400 2022-09-29 20:52 vendor/log/src/kv/key.rs
```

Seems like an improvment. Are there any more ideas we can take from either of the links at https://github.com/stratis-storage/ci/issues/301#issuecomment-1262700552 ?

**Comment by bgurney-rh** [comment]
I see this:
```
$ tar tvf SOURCES/stratisd-3.3.0~20220930git0e7d790b-vendor.tar.gz | head
drwxr-xr-x 0/0               0 2022-09-30 08:41 vendor/
drwxr-xr-x 0/0               0 2022-09-30 08:41 vendor/windows_x86_64_msvc/
drwxr-xr-x 0/0               0 2022-09-30 08:41 vendor/windows_x86_64_msvc/src/
-rw-r--r-- 0/0              11 2022-09-30 08:41 vendor/windows_x86_64_msvc/src/lib.rs
drwxr-xr-x 0/0               0 2022-09-30 08:41 vendor/windows_x86_64_msvc/lib/
-rw-r--r-- 0/0         4345164 2022-09-30 08:41 vendor/windows_x86_64_msvc/lib/windows.lib
-rw-r--r-- 0/0             789 2022-09-30 08:41 vendor/windows_x86_64_msvc/Cargo.toml
-rw-r--r-- 0/0             333 2022-09-30 08:41 vendor/windows_x86_64_msvc/build.rs
-rw-r--r-- 0/0             411 2022-09-30 08:41 vendor/windows_x86_64_msvc/.cargo-checksum.json
drwxr-xr-x 0/0               0 2022-09-30 08:41 vendor/retry/
```

There's a few other options I could add from those links, but they don't address the permissions difference between our examples.

**Comment by mulkieran** [comment]
From GitHub generated tarfile:
```
amulhern@amulhern new_folder]$ tar tvf stratisd-3.2.3.tar.gz  | head -5
drwxrwxr-x root/root         0 2022-08-28 11:28 stratisd-3.2.3/
-rw-rw-r-- root/root        16 2022-08-28 11:28 stratisd-3.2.3/.clippy.toml
drwxrwxr-x root/root         0 2022-08-28 11:28 stratisd-3.2.3/.githooks/
-rwxrwxr-x root/root       249 2022-08-28 11:28 stratisd-3.2.3/.githooks/pre-commit
drwxrwxr-x root/root         0 2022-08-28 11:28 stratisd-3.2.3/.github/
```

**Review by mulkieran — APPROVED** [review]

**Comment by mulkieran** [comment]
Awaiting advice on umask value

**Comment by bgurney-rh** [comment]
Dropped commit 11c4f76 ("Use umask 007 for package and vendor steps").

**Review by mulkieran — APPROVED** [review]

**Pull request merged**
