### PR TITLE
ci stratisd: change RUST_LOG from debug to info

### PR DESCRIPTION
**Pull request by bgurney-rh**

### CODE REVIEW

**Comment by bgurney-rh** [comment]
On a test run, the number of output lines during the 27 stratisd tests went from 3750 to 83.

**Comment by bgurney-rh** [comment]
Fixes #43

**Comment by mulkieran** [comment]
> On a test run, the number of output lines during the 27 stratisd tests went from 3750 to 83.

That does seem more manageable.

**Comment by mulkieran** [comment]
I'll merge this now, since the excessive logging does get in the way.

**Pull request merged**
