### PR TITLE
Run CI Python tasks on Fedora container

### PR DESCRIPTION
**Pull request by bgurney-rh**
Related: stratis-storage/project#294

### CODE REVIEW

**Comment by mulkieran** [comment]
Want to get equivalent testing PR completely done.

**Comment by bgurney-rh** [comment]
Could the F29 CI pylint error be related to a pygithub version difference?  (F29 has 1.39; a "make lint" run on F34 passes, with pygithub 1.54.)

**Comment by mulkieran** [comment]
> Could the F29 CI pylint error be related to a pygithub version difference? (F29 has 1.39; a "make lint" run on F34 passes, with pygithub 1.54.)

@bgurney-rh That is surely the reason. The best thing to do for this one is to figure out how to run pylint on all the other for LOWEST SUPPORTED, but not this script. You might need a second Makefile target or to relocate the scripts to different directories, or both.

**Comment by bgurney-rh** [comment]
That seemed to work.  The current lint job can lint `batch_cancel.py`.

**Review by mulkieran — CHANGES_REQUESTED** [review]
Looks good! Please close this and open a new final PR.

**Pull request closed without merging**
