### PR TITLE
For check, compile but do not run any tests

### PR DESCRIPTION
**Pull request by mulkieran**

### CODE REVIEW

**Comment by bgurney-rh** [comment]
On trying this, the "Doc-tests stratisd" stage failed with this error: `Unrecognized option: 'no-run'`

**Comment by mulkieran** [comment]
@bgurney-rh Could you post the precise failing command, as it is expanded in your test run. On rawhide, my command was ```/usr/bin/env CARGO_HOME=.cargo RUSTC_BOOTSTRAP=1 'RUSTFLAGS=-Copt-level=3 -Cdebuginfo=2 -Ccodegen-units=1 -Clink-arg=-Wl,-z,relro -Clink-arg=-Wl,-z,now -Clink-arg=-Wl,-dT,/builddir/build/BUILD/stratisd-3.0.4/.package_note-stratisd-3.0.4-6.fc37.x86_64.ld --cap-lints=warn' /usr/bin/cargo test -j6 -Z avoid-dev-deps --release --no-fail-fast --no-run```, which succeeded, of course. There is probably a difference in how the macro is expanded.

**Comment by bgurney-rh** [comment]
On f35, I see this:
```
$ rpm --eval '%{cargo_test} -- --no-run'
/usr/bin/env CARGO_HOME=.cargo /usr/bin/cargo test --release -j6 --no-fail-fast -- --no-run
```
...though that's defined from `/usr/lib/rpm/macros.d/macros.rust-toolset`.  I'm not sure what's defining this macro on your system.

**Comment by mulkieran** [comment]
My command is picked from the most recent koji build logs for stratisd for rawhide.

Are you able to look at any build logs from your test and see the command that is being run? Somewhere those logs will contain the string "cargo test", hopefully.

**Comment by bgurney-rh** [comment]
The blackbox tests build with rust-toolset, while the macro that Koji used is likely coming from rust-packaging.  Therefore, the macro behavior for `%cargo_test` is most likely different between them.

**Comment by mulkieran** [comment]
> The blackbox tests build with rust-toolset, while the macro that Koji used is likely coming from rust-packaging. Therefore, the macro behavior for `%cargo_test` is most likely different between them.

Yes, we've had a similar problem w/ ```%{cargo-build}``` being different in the particular way in which it parses arguments, and that is probably what is happening here. I'm going to try to remove the '--'. Please test again.

**Comment by bgurney-rh** [comment]
This works!  The `%check` phase completed successfully, the packages successfully built, and all blackbox tests passed.

**Comment by mulkieran** [comment]
Ok, squashed.

**Review by bgurney-rh — APPROVED** [review]
Tested the squashed commit; packages build, and all tests pass.

**Pull request merged**
