### PR TITLE
ci: increase rustup default to 1.37

### PR DESCRIPTION
**Pull request by bgurney-rh**
Related: https://github.com/stratis-storage/project/issues/88.

### CODE REVIEW

**Comment by mulkieran** [comment]
Is 1.37 available on RHEL8? We run Jenkins CI w/ the "lowest supported compiler". The separate concept "recommended development compiler" also exists and we have already bumped that up to 3.7. We want to make sure that "lowest supported compiler" <= "recommended development compiler", but they don't have to be the same. If we're bumping up the versions in CI, we should also bump "lowest supported compiler" on Travis builds (and vice-versa).

**Comment by bgurney-rh** [comment]
Okay; I'll stage this back into "In progress", for when we're ready to advance CI to 1.37.

**Comment by mulkieran** [comment]
The release went into verified in RHEL8 six days ago, so we might as well go ahead.

**Comment by bgurney-rh** [comment]
Rebased.

**Pull request merged**
